services:
  php:
    build: .
    volumes:
      - .:/var/www/html
      - ./apache.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: pass
    depends_on:
      - db

volumes:
  db_data: